# Generated by Django 3.2.5 on 2021-08-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('indicators', '0033_alter_variable_aggregation_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('geog_type', models.CharField(max_length=100)),
                ('number_format_options', models.JSONField()),
                ('use_percent', models.BooleanField()),
                ('data', models.BinaryField()),
                ('geog_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('time_axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.timeaxis')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.variable')),
            ],
            options={
                'unique_together': {('geog_content_type', 'variable')},
            },
        ),
    ]
