# Generated by Django 3.2.5 on 2021-08-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='number_format_options',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='map',
            name='use_percent',
            field=models.BooleanField(default=False),
        ),
    ]
