# Generated by Django 3.2.5 on 2021-08-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0034_auto_20210820_1117'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('maps', '0002_auto_20210818_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='DataLayer',
        ),
        migrations.AlterUniqueTogether(
            name='datalayer',
            unique_together={('geog_content_type', 'variable', 'time_axis')},
        ),
    ]
