# Generated by Django 3.2 on 2022-07-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20220113_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalayer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
