# Generated by Django 3.2.5 on 2021-08-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20210820_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalayer',
            name='data',
        ),
    ]
