# Generated by Django 3.2.5 on 2021-09-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_remove_datalayer_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='label',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
