# Generated by Django 3.2 on 2022-08-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_ckanlayer_maplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckanlayer',
            name='package_id',
        ),
        migrations.AddField(
            model_name='ckanlayer',
            name='image_field',
            field=models.CharField(default='image', max_length=100),
        ),
    ]
