# Generated by Django 3.2 on 2022-08-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maps', '0008_auto_20220829_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplayer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='maplayer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_maps.maplayer_set+', to='contenttypes.contenttype'),
        ),
    ]
