# Generated by Django 3.2 on 2022-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20220829_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckanlayer',
            name='extra_fields',
        ),
        migrations.AlterField(
            model_name='ckanlayer',
            name='geom_field',
            field=models.CharField(blank=True, default='_geom', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ckanlayer',
            name='id_field',
            field=models.CharField(blank=True, default='_id', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ckanlayer',
            name='image_field',
            field=models.CharField(blank=True, default='image', max_length=100, null=True),
        ),
    ]
