# Generated by Django 3.2 on 2022-08-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20220829_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckanlayer',
            name='image_field',
            field=models.CharField(blank=True, help_text='Leave blank if no image', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ckanlayer',
            name='sql_override',
            field=models.TextField(blank=True, null=True),
        ),
    ]
