# Generated by Django 3.2 on 2022-08-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_auto_20220829_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ckanlayer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='ckanlayer',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='ckanlayer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ckanlayer',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='ckanlayer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ckanlayer',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='ckanlayer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ckanlayer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ckanlayer',
            name='tags',
        ),
        migrations.AddField(
            model_name='ckanlayer',
            name='geom_webmercator_field',
            field=models.CharField(blank=True, default='_geom_webmercator', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ckanlayer',
            name='maplayer_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maps.maplayer'),
            preserve_default=False,
        ),
    ]
