# Generated by Django 3.2 on 2022-08-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20220829_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='layers_override',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='source_override',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
