# Generated by Django 3.2 on 2022-08-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_ckanlayer_srid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckanlayer',
            name='srid',
            field=models.IntegerField(default=4326, verbose_name='SRID'),
        ),
    ]
