# Generated by Django 3.2 on 2022-08-29 23:56

import colorfield.fields
from django.db import migrations, models
import maps.models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_alter_ckanlayer_srid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckanlayer',
            name='primary_color',
            field=colorfield.fields.ColorField(default=maps.models.random_color, image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='ckanlayer',
            name='secondary_color',
            field=colorfield.fields.ColorField(default=maps.models.random_color, image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='ckanlayer',
            name='geom_webmercator_field',
            field=models.CharField(blank=True, default='_the_geom_webmercator', max_length=100, null=True),
        ),
    ]
