# Generated by Django 3.2 on 2022-08-30 01:06

import colorfield.fields
from django.db import migrations, models
import maps.models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_auto_20220829_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckanlayer',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='ckanlayer',
            name='secondary_color',
        ),
        migrations.AddField(
            model_name='maplayer',
            name='color_scale',
            field=models.CharField(choices=[], default='YlGn', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maplayer',
            name='primary_color',
            field=colorfield.fields.ColorField(default=maps.models.random_color, image_field=None, max_length=18, samples=None),
        ),
    ]
