# Generated by Django 3.2 on 2022-08-30 02:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_auto_20220830_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckanlayer',
            name='categories_override',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='ckanlayer',
            name='category_field',
            field=models.CharField(blank=True, help_text='Leave blank to not color by category', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='fill_layout_override',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='fill_paint_override',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='line_layout_override',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='line_paint_override',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='point_layout_override',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='point_paint_override',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='color_scale',
            field=models.CharField(choices=[('YlGn', 'YlGn'), ('YlGnBu', 'YlGnBu'), ('GnBu', 'GnBu'), ('BuGn', 'BuGn'), ('PuBuGn', 'PuBuGn'), ('PuBu', 'PuBu'), ('BuPu', 'BuPu'), ('RdPu', 'RdPu'), ('PuRd', 'PuRd'), ('OrRd', 'OrRd'), ('YlOrRd', 'YlOrRd'), ('YlOrBr', 'YlOrBr'), ('Purples', 'Purples'), ('Blues', 'Blues'), ('Greens', 'Greens'), ('Oranges', 'Oranges'), ('Reds', 'Reds'), ('Greys', 'Greys'), ('PuOr', 'PuOr'), ('BrBG', 'BrBG'), ('PRGn', 'PRGn'), ('PiYG', 'PiYG'), ('RdBu', 'RdBu'), ('RdGy', 'RdGy'), ('RdYlBu', 'RdYlBu'), ('Spectral', 'Spectral'), ('RdYlGn', 'RdYlGn'), ('Accent', 'Accent'), ('Dark2', 'Dark2'), ('Paired', 'Paired'), ('Pastel1', 'Pastel1'), ('Pastel2', 'Pastel2'), ('Set1', 'Set1'), ('Set2', 'Set2'), ('Set3', 'Set3')], max_length=100),
        ),
    ]
