# Generated by Django 3.2 on 2022-11-10 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_auto_20221110_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorlayer',
            name='color_scale_buckets',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
