services:
  tiles:
    image: maplibre/martin
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file: .env

  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /code
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    depends_on:
      - db

  cache:
    image: memcached
    env_file: .env

