services:
  tiles:
    image: maplibre/martin
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file: .env
    networks:
      main:
        aliases:
          - tiles
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /code
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    networks:
      main:
        aliases:
          - api
    depends_on:
      - db

  db:
    image: postgis/postgis
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      main:
       aliases:
        - db


  cache:
    image: memcached
    env_file: .env
    networks:
      main:
        aliases:
          - cache

