# Generated by Django 3.2 on 2022-05-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextitem',
            name='tags',
            field=models.ManyToManyField(to='context.Tag'),
        ),
    ]
