# Shadyside total population
# Single geography that requires geographic aggregation
GET http://localhost:8000/data-viz/total-population-bv/?geogType=neighborhood&geogID=pgh-hood-56
Accept: application/json

###

# Percent population under 18 across counties
# Multiple geographies with direct data each
GET http://localhost:8000/data-viz/pop-under18-map/?geogType=county&geogID=42003
Accept: application/json

###
