# Mismatched regionType and geoid
GET http://localhost:8000/data-viz/57/?regionType=tract&geoid=42003
Accept: application/json

###
# Tile Request
GET http://localhost:8000/map_layer/tract/40/207
Accept: application/json


###
# Working Dataviz data Request
GET http://localhost:8000/data-viz/57/?regionType=tract&geoid=42003070900
Accept: application/json

###
# Working region request
GET http://localhost:8000/geo/region/?regionType=tract&geoid=42003070900
Accept: application/json


###
# Working region request
GET http://localhost:8000/geo/region/?regionType=tract&geoid=42003070900
Accept: application/json

###
GET http://localhost:8000/data-viz/34/?geogType=tract&geogID=42003040400
Accept: application/json