# Generated by Django 3.2.7 on 2021-10-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census_data', '0003_auto_20211021_2006'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusvariablesource',
            name='census_table_records',
            field=models.ManyToManyField(to='census_data.CensusTableRecord'),
        ),
        migrations.AlterUniqueTogether(
            name='censusvariablesource',
            unique_together={('variable', 'source')},
        ),
        migrations.AlterIndexTogether(
            name='censusvariablesource',
            index_together={('variable', 'source')},
        ),
        migrations.RemoveField(
            model_name='censusvariablesource',
            name='census_table_pointers',
        ),
    ]
