# Generated by Django 3.0.3 on 2020-10-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vizvariable',
            options={'ordering': ['order'], 'verbose_name': 'Visualization Variable', 'verbose_name_plural': 'Visualization Variables'},
        ),
        migrations.RenameField(
            model_name='dataviz',
            old_name='variables',
            new_name='vars',
        ),
    ]
