# Generated by Django 3.1.5 on 2021-01-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census_data', '0001_initial'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusvariablesource',
            name='census_tables',
            field=models.ManyToManyField(to='census_data.CensusTable'),
        ),
        migrations.AlterField(
            model_name='censusvariablesource',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
