# Generated by Django 3.1.5 on 2021-01-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census_data', '0002_censustablepointer'),
        ('indicators', '0002_auto_20210128_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusvariablesource',
            name='census_tables',
            field=models.ManyToManyField(to='census_data.CensusTablePointer'),
        ),
    ]
