# Generated by Django 3.2.7 on 2021-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20211021_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='use_percent',
            field=models.BooleanField(default=False),
        ),
    ]
