# Generated by Django 3.1.5 on 2021-01-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census_data', '0003_auto_20210128_2341'),
        ('indicators', '0003_auto_20210128_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censusvariablesource',
            name='census_tables',
        ),
        migrations.AddField(
            model_name='censusvariablesource',
            name='census_table_pointers',
            field=models.ManyToManyField(to='census_data.CensusTablePointer'),
        ),
    ]
