# Generated by Django 3.2.7 on 2021-11-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_alter_maplayer_use_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='aggregation_method',
            field=models.CharField(choices=[('NONE', 'None'), ('COUNT', 'Count'), ('SUM', 'Sum'), ('AVG', 'Mean'), ('MODE', 'Mode'), ('MAX', 'Maximum'), ('MIN', 'Minimum')], default='SUM', help_text='Used when having to describe a geography by combining values from smaller geographies. Select "None" if this value cannot be used in aggregate functions.', max_length=5),
        ),
    ]
