# Generated by Django 3.1.5 on 2021-02-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_auto_20210128_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maplayer',
            old_name='map',
            new_name='minimap',
        ),
    ]
