# Generated by Django 3.2.9 on 2022-01-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_alter_variable_aggregation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_style',
            field=models.CharField(choices=[('Default', 'default'), ('Demographics', 'demographics')], default='demographics', max_length=40),
            preserve_default=False,
        ),
    ]
