# Generated by Django 3.2.9 on 2022-01-13 20:20

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_table_table_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataviz',
            name='full_description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='full_description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='full_description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='full_description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='full_description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True),
        ),
        migrations.AddField(
            model_name='timeaxis',
            name='full_description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='full_description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='description',
            field=models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='description',
            field=models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='timeaxis',
            name='description',
            field=models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description'),
        ),
    ]
