# Generated by Django 3.1.5 on 2021-02-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20210204_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckanvariable',
            name='carto_table',
        ),
        migrations.AddField(
            model_name='variable',
            name='carto_table',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
