# Generated by Django 3.2.11 on 2022-01-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20220113_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censussource',
            options={'verbose_name': 'Census/ACS Source', 'verbose_name_plural': 'Census/ACS Sources'},
        ),
        migrations.AlterModelOptions(
            name='censusvariable',
            options={'verbose_name': 'Census Variable', 'verbose_name_plural': 'Census Variables'},
        ),
        migrations.AlterModelOptions(
            name='ckansource',
            options={'verbose_name': 'CKAN Source', 'verbose_name_plural': 'CKAN Sources'},
        ),
        migrations.AlterModelOptions(
            name='ckanvariable',
            options={'verbose_name': 'CKAN Variable', 'verbose_name_plural': 'CKAN Variables'},
        ),
        migrations.AlterModelOptions(
            name='timeaxis',
            options={'verbose_name': 'Time Axis', 'verbose_name_plural': 'Time Axes'},
        ),
        migrations.AlterField(
            model_name='indicator',
            name='long_description',
            field=models.TextField(blank=True, help_text='🛑 Deprecated!!! This field will go away soon. Used "Full Description" instead.', null=True),
        ),
    ]
