# Generated by Django 3.1.5 on 2021-02-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('indicators', '0007_auto_20210205_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyledGeogMapLayer',
            fields=[
                ('maplayer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicators.maplayer')),
                ('sub_geog', models.ForeignKey(blank=True, help_text='If provided, this geography will be styled within the target geography.  Otherwise, the provided geography will be styled along with others of the same level.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.censusgeography')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('indicators.maplayer',),
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='limit_to_target_geog',
        ),
        migrations.AddField(
            model_name='objectslayer',
            name='limit_to_target_geog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parcelslayer',
            name='limit_to_target_geog',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ChoroplethLayer',
        ),
    ]
