# Generated by Django 3.2.11 on 2022-01-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_auto_20220114_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableRow',
            new_name='TableVariable',
        ),
        migrations.RemoveField(
            model_name='table',
            name='transpose',
        ),
        migrations.AddField(
            model_name='table',
            name='column_axis',
            field=models.CharField(choices=[('Geography', 'geography'), ('Variable', 'variable'), ('Time', 'time')], default='time', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='row_axis',
            field=models.CharField(choices=[('Geography', 'geography'), ('Variable', 'variable'), ('Time', 'time')], default='variable', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='view_axis',
            field=models.CharField(choices=[('Geography', 'geography'), ('Variable', 'variable'), ('Time', 'time')], default='geography', max_length=20),
        ),
    ]
