# Generated by Django 3.1.5 on 2021-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_auto_20210209_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='barchartpart',
            name='style',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('HI', 'Highlight'), ('SU', 'Subtle'), ('AVG', 'Avg/Mean')], default=None, max_length=4, null=True, verbose_name='Special Style'),
        ),
    ]
