# Generated by Django 3.2 on 2022-03-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_auto_20220114_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarChart',
            fields=[
                ('dataviz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicators.dataviz')),
                ('legend_type', models.CharField(choices=[('line', 'Line'), ('square', 'Square'), ('rect', 'Rectangle'), ('circle', 'Circle'), ('cross', 'Cross'), ('diamond', 'Diamond'), ('star', 'Star'), ('triangle', 'Triangle'), ('wye', 'Wye'), ('none', 'None')], default='circle', max_length=10)),
                ('as_columns', models.BooleanField(default=False, help_text='constraints may require apps and sites to override to bar chart when space is limited.', verbose_name='Prefer column layout')),
                ('across_geogs', models.BooleanField(default=False, help_text='Check if you want this chart to compare the statistic across geographies instead of across time')),
            ],
            options={
                'abstract': False,
            },
            bases=('indicators.dataviz',),
        ),
        migrations.CreateModel(
            name='BarChartPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_to_bar_chart', to='indicators.variable')),
                ('viz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_chart_to_variable', to='indicators.barchart')),
            ],
            options={
                'unique_together': {('viz', 'variable', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Histogram',
            fields=[
                ('dataviz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicators.dataviz')),
                ('legend_type', models.CharField(choices=[('line', 'Line'), ('square', 'Square'), ('rect', 'Rectangle'), ('circle', 'Circle'), ('cross', 'Cross'), ('diamond', 'Diamond'), ('star', 'Star'), ('triangle', 'Triangle'), ('wye', 'Wye'), ('none', 'None')], default='circle', max_length=10)),
                ('n_buckets', models.IntegerField(default=0, help_text='0 = auto', verbose_name='Number of buckets')),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.variable', verbose_name='Distribution variable')),
            ],
            options={
                'abstract': False,
            },
            bases=('indicators.dataviz',),
        ),
        migrations.CreateModel(
            name='LineChart',
            fields=[
                ('dataviz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicators.dataviz')),
                ('legend_type', models.CharField(choices=[('line', 'Line'), ('square', 'Square'), ('rect', 'Rectangle'), ('circle', 'Circle'), ('cross', 'Cross'), ('diamond', 'Diamond'), ('star', 'Star'), ('triangle', 'Triangle'), ('wye', 'Wye'), ('none', 'None')], default='circle', max_length=10)),
                ('as_area', models.BooleanField(verbose_name='As stacked area chart')),
            ],
            options={
                'abstract': False,
            },
            bases=('indicators.dataviz',),
        ),
        migrations.CreateModel(
            name='LineChartPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_to_line_chart', to='indicators.variable')),
                ('viz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_chart_to_variable', to='indicators.linechart')),
            ],
            options={
                'unique_together': {('viz', 'variable', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PieChart',
            fields=[
                ('dataviz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicators.dataviz')),
                ('legend_type', models.CharField(choices=[('line', 'Line'), ('square', 'Square'), ('rect', 'Rectangle'), ('circle', 'Circle'), ('cross', 'Cross'), ('diamond', 'Diamond'), ('star', 'Star'), ('triangle', 'Triangle'), ('wye', 'Wye'), ('none', 'None')], default='circle', max_length=10)),
                ('as_donut', models.BooleanField(verbose_name='As donut chart')),
            ],
            options={
                'abstract': False,
            },
            bases=('indicators.dataviz',),
        ),
        migrations.CreateModel(
            name='PieChartPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_to_pie_chart', to='indicators.variable')),
                ('viz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pie_chart_to_variable', to='indicators.piechart')),
            ],
            options={
                'unique_together': {('viz', 'variable', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PyramidChart',
            fields=[
                ('dataviz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicators.dataviz')),
                ('legend_type', models.CharField(choices=[('line', 'Line'), ('square', 'Square'), ('rect', 'Rectangle'), ('circle', 'Circle'), ('cross', 'Cross'), ('diamond', 'Diamond'), ('star', 'Star'), ('triangle', 'Triangle'), ('wye', 'Wye'), ('none', 'None')], default='circle', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('indicators.dataviz',),
        ),
        migrations.CreateModel(
            name='PyramidChartLeftPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_to_left_pyramid_chart', to='indicators.variable')),
                ('viz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_pyramid_chart_to_variable', to='indicators.pyramidchart')),
            ],
            options={
                'unique_together': {('viz', 'variable', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PyramidChartRightPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_to_right_pyramid_chart', to='indicators.variable')),
                ('viz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_pyramid_chart_to_variable', to='indicators.pyramidchart')),
            ],
            options={
                'unique_together': {('viz', 'variable', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ScatterPlot',
            fields=[
                ('dataviz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicators.dataviz')),
                ('legend_type', models.CharField(choices=[('line', 'Line'), ('square', 'Square'), ('rect', 'Rectangle'), ('circle', 'Circle'), ('cross', 'Cross'), ('diamond', 'Diamond'), ('star', 'Star'), ('triangle', 'Triangle'), ('wye', 'Wye'), ('none', 'None')], default='circle', max_length=10)),
                ('x_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_scatter_plot', to='indicators.variable', verbose_name='Horizontal axis variable')),
                ('y_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y_scatter_plot', to='indicators.variable', verbose_name='Vertical axis variable')),
            ],
            options={
                'abstract': False,
            },
            bases=('indicators.dataviz',),
        ),
        migrations.AlterUniqueTogether(
            name='chartpart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chartpart',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='chartpart',
            name='viz',
        ),
        migrations.AlterField(
            model_name='bigvalue',
            name='format',
            field=models.TextField(choices=[('PLN', 'The value'), ('FRN', 'Approximate, human friendly, fraction: value over denominator.'), ('PCT', "The value's percent of denominator"), ('BTH', 'Percent and Fraction')], default='PLN', help_text="Only use percent for numbers with denominators. Variables with 'percent' as a unit should use 'Plain'", max_length=3),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='indicators.domain'),
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.DeleteModel(
            name='ChartPart',
        ),
        migrations.AddField(
            model_name='pyramidchart',
            name='left_vars',
            field=models.ManyToManyField(related_name='left_pyramid_chart', through='indicators.PyramidChartLeftPart', to='indicators.Variable', verbose_name='Left bars'),
        ),
        migrations.AddField(
            model_name='pyramidchart',
            name='right_vars',
            field=models.ManyToManyField(related_name='right_pyramid_chart', through='indicators.PyramidChartRightPart', to='indicators.Variable', verbose_name='Right bars'),
        ),
        migrations.AddField(
            model_name='piechart',
            name='vars',
            field=models.ManyToManyField(through='indicators.PieChartPart', to='indicators.Variable', verbose_name='Sections'),
        ),
        migrations.AddField(
            model_name='linechart',
            name='vars',
            field=models.ManyToManyField(through='indicators.LineChartPart', to='indicators.Variable', verbose_name='Lines'),
        ),
        migrations.AddField(
            model_name='barchart',
            name='vars',
            field=models.ManyToManyField(through='indicators.BarChartPart', to='indicators.Variable', verbose_name='Rows'),
        ),
    ]
