# Generated by Django 3.2 on 2022-03-04 19:34

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_auto_20220303_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description')),
                ('full_description', markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True)),
                ('domains', models.ManyToManyField(related_name='project', to='indicators.Domain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
