# Generated by Django 3.1.5 on 2021-02-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_barchartpart_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='short_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
