# Generated by Django 3.2 on 2022-03-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_taxonomy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'verbose_name': 'Taxonomy', 'verbose_name_plural': 'Taxonomies'},
        ),
        migrations.RemoveField(
            model_name='domain',
            name='order',
        ),
        migrations.CreateModel(
            name='TaxonomyDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_to_taxonomy', to='indicators.taxonomy')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_to_domain', to='indicators.taxonomy')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('taxonomy', 'domain')},
            },
        ),
    ]
