# Generated by Django 3.1.5 on 2021-03-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_variable_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigvalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={},
        ),
        migrations.AddField(
            model_name='minimap',
            name='toggle_layers',
            field=models.BooleanField(default=False, help_text='If true, only one layer can be visible at a time'),
        ),
    ]
