# Generated by Django 3.1.5 on 2021-03-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_auto_20210301_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minimap',
            name='toggle_layers',
        ),
        migrations.AddField(
            model_name='dataviz',
            name='height_override',
            field=models.IntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], help_text='Relative height when displayed in a grid with other data presentations.', null=True),
        ),
        migrations.AddField(
            model_name='dataviz',
            name='width_override',
            field=models.IntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], help_text='Relative width when displayed in a grid with other data presentations.', null=True),
        ),
    ]
