# Generated by Django 3.2 on 2022-03-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_auto_20220304_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='domains',
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='_domains',
            field=models.ManyToManyField(related_name='project', through='indicators.TaxonomyDomain', to='indicators.Domain'),
        ),
        migrations.AlterField(
            model_name='taxonomydomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_to_taxonomy', to='indicators.domain'),
        ),
    ]
