# Generated by Django 3.1.5 on 2021-03-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0012_auto_20210302_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='short_name',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
