# Generated by Django 3.2 on 2022-05-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_auto_20220520_1523'),
        ('indicators', '0013_auto_20220520_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatordataviz',
            name='primary',
            field=models.BooleanField(default=False, help_text='prioritized for display in the indicator card'),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='tags',
            field=models.ManyToManyField(blank=True, to='context.Tag'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='tags',
            field=models.ManyToManyField(blank=True, to='context.Tag'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='tags',
            field=models.ManyToManyField(blank=True, to='context.Tag'),
        ),
        migrations.AlterField(
            model_name='source',
            name='tags',
            field=models.ManyToManyField(blank=True, to='context.Tag'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='tags',
            field=models.ManyToManyField(blank=True, to='context.Tag'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='tags',
            field=models.ManyToManyField(blank=True, to='context.Tag'),
        ),
        migrations.AlterField(
            model_name='timeaxis',
            name='tags',
            field=models.ManyToManyField(blank=True, to='context.Tag'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='tags',
            field=models.ManyToManyField(blank=True, to='context.Tag'),
        ),
    ]
