# Generated by Django 3.1.5 on 2021-03-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('indicators', '0013_auto_20210302_2323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StyledGeogMapLayer',
            new_name='GeogChoroplethMapLayer',
        ),
    ]
