# Generated by Django 3.1.5 on 2021-03-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_auto_20210303_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censusvariablesource',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='carto_table',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='field_in_carto',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='sql_filter_for_carto',
        ),
        migrations.AddField(
            model_name='barchart',
            name='across_geogs',
            field=models.BooleanField(default=False, help_text='Check if you want this chart to compare the statistic across geographies instead of across time'),
        ),
        migrations.AddField(
            model_name='linechart',
            name='across_geogs',
            field=models.BooleanField(default=False, help_text='Check if you want this chart to compare the statistic across geographies instead of across time'),
        ),
        migrations.AddField(
            model_name='piechart',
            name='across_geogs',
            field=models.BooleanField(default=False, help_text='Check if you want this chart to compare the statistic across geographies instead of across time'),
        ),
        migrations.AddField(
            model_name='populationpyramidchart',
            name='across_geogs',
            field=models.BooleanField(default=False, help_text='Check if you want this chart to compare the statistic across geographies instead of across time'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='units',
            field=models.CharField(blank=True, help_text='Special format for $.  Otherwise, often displayed after value.', max_length=30, null=True),
        ),
    ]
