# Generated by Django 3.2 on 2022-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_auto_20220520_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordataviz',
            name='primary',
            field=models.BooleanField(default=False, help_text='prioritize this data viz for display in the indicator card'),
        ),
    ]
