# Generated by Django 3.2 on 2022-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_auto_20220520_1523'),
        ('indicators', '0015_alter_indicatordataviz_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='context',
            field=models.ManyToManyField(blank=True, to='context.ContextItem'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='context',
            field=models.ManyToManyField(blank=True, to='context.ContextItem'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='context',
            field=models.ManyToManyField(blank=True, to='context.ContextItem'),
        ),
        migrations.AlterField(
            model_name='source',
            name='context',
            field=models.ManyToManyField(blank=True, to='context.ContextItem'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='context',
            field=models.ManyToManyField(blank=True, to='context.ContextItem'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='context',
            field=models.ManyToManyField(blank=True, to='context.ContextItem'),
        ),
        migrations.AlterField(
            model_name='timeaxis',
            name='context',
            field=models.ManyToManyField(blank=True, to='context.ContextItem'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='context',
            field=models.ManyToManyField(blank=True, to='context.ContextItem'),
        ),
    ]
