# Generated by Django 3.1.7 on 2021-03-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0016_auto_20210317_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckanregionalsource',
            name='schooldistrict_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School District field'),
        ),
        migrations.AddField(
            model_name='ckanregionalsource',
            name='schooldistrict_field_is_sql',
            field=models.BooleanField(default=False),
        ),
    ]
