# Generated by Django 3.2 on 2022-05-25 19:46

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_auto_20220520_1523'),
        ('indicators', '0016_auto_20220525_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdomainTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomain_to_topic', to='indicators.subdomain')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description')),
                ('full_description', markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True)),
                ('long_description', models.TextField(blank=True, help_text='🛑 Deprecated!!! This field will go away soon. Used "Full Description" instead.', null=True)),
                ('limitations', models.TextField(blank=True, help_text='Describe what limitations the data may have (e.g. small sample size, difficulties in collecting data', null=True)),
                ('importance', models.TextField(blank=True, help_text='Describe the data collection process, highlighting areas where bias and assumptions made during the collection can impact how the data are interpreted', null=True)),
                ('source', models.TextField(blank=True, help_text='Describe the data collection process, highlighting areas where bias and assumptions made during the collection can impact how the data are interpreted', null=True)),
                ('provenance', models.TextField(blank=True, help_text='Describe the data collection process, highlighting areas where bias and assumptions made during the collection can impact how the data are interpreted', null=True)),
                ('context', models.ManyToManyField(blank=True, to='context.ContextItem')),
                ('tags', models.ManyToManyField(blank=True, to='context.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicDataViz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('primary', models.BooleanField(default=False, help_text='prioritize this data viz for display in the topic card')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='indicatordataviz',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='indicatordataviz',
            name='data_viz',
        ),
        migrations.RemoveField(
            model_name='indicatordataviz',
            name='indicator',
        ),
        migrations.AlterUniqueTogether(
            name='subdomainindicator',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subdomainindicator',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='subdomainindicator',
            name='subdomain',
        ),
        migrations.RemoveField(
            model_name='dataviz',
            name='indicator',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.AddField(
            model_name='topicdataviz',
            name='data_viz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataviz_to_topic', to='indicators.dataviz'),
        ),
        migrations.AddField(
            model_name='topicdataviz',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_to_dataviz', to='indicators.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='vizes',
            field=models.ManyToManyField(related_name='topic', through='indicators.TopicDataViz', to='indicators.DataViz'),
        ),
        migrations.AddField(
            model_name='subdomaintopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_to_subdomain', to='indicators.topic'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='inds',
            field=models.ManyToManyField(related_name='subdomains', through='indicators.SubdomainTopic', to='indicators.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='topicdataviz',
            unique_together={('topic', 'data_viz')},
        ),
        migrations.AlterUniqueTogether(
            name='subdomaintopic',
            unique_together={('subdomain', 'topic')},
        ),
    ]
