# Generated by Django 3.2 on 2022-05-26 22:00

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_auto_20220520_1523'),
        ('indicators', '0017_auto_20220525_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description')),
                ('full_description', markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True)),
                ('across_geogs', models.BooleanField(default=True, help_text='Leave true in nearly all cases.', verbose_name='Allow cross-geog vizes')),
                ('note', markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Brief note')),
                ('use_columns', models.BooleanField(default=False, help_text='constraints may require apps and sites to override to bar chart when space is limited.', verbose_name='Prefer column layout in bar charts (if any)')),
                ('use_denominators', models.BooleanField(default=True, help_text='(Usually left true)', verbose_name='Use denominators and percents in visualizations')),
                ('context', models.ManyToManyField(blank=True, to='context.ContextItem')),
                ('mirror_indicator', models.OneToOneField(blank=True, help_text='e.g. pop-by-age-male if this indicator is pop-my-age-female would allow a pyramid chart', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.indicator')),
                ('tags', models.ManyToManyField(blank=True, to='context.Tag')),
                ('time_axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='indicators.timeaxis')),
            ],
            options={
                'verbose_name': 'Data Visualization',
                'verbose_name_plural': 'Data Visualizations',
            },
        ),
        migrations.CreateModel(
            name='IndicatorVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_to_variable', to='indicators.indicator')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_to_indicator', to='indicators.variable')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopicIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('primary', models.BooleanField(default=False, help_text='prioritize this indicator for display in the topic card')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_to_topic', to='indicators.indicator')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='barchartpart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='barchartpart',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='barchartpart',
            name='viz',
        ),
        migrations.RemoveField(
            model_name='bigvalue',
            name='dataviz_ptr',
        ),
        migrations.RemoveField(
            model_name='bigvalue',
            name='vars',
        ),
        migrations.AlterUniqueTogether(
            name='bigvaluevariable',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bigvaluevariable',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='bigvaluevariable',
            name='viz',
        ),
        migrations.RemoveField(
            model_name='dataviz',
            name='context',
        ),
        migrations.RemoveField(
            model_name='dataviz',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='dataviz',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='dataviz',
            name='time_axis',
        ),
        migrations.RemoveField(
            model_name='histogram',
            name='dataviz_ptr',
        ),
        migrations.RemoveField(
            model_name='histogram',
            name='var',
        ),
        migrations.RemoveField(
            model_name='linechart',
            name='dataviz_ptr',
        ),
        migrations.RemoveField(
            model_name='linechart',
            name='vars',
        ),
        migrations.AlterUniqueTogether(
            name='linechartpart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='linechartpart',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='linechartpart',
            name='viz',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='viz',
        ),
        migrations.RemoveField(
            model_name='minimap',
            name='dataviz_ptr',
        ),
        migrations.RemoveField(
            model_name='minimap',
            name='vars',
        ),
        migrations.RemoveField(
            model_name='piechart',
            name='dataviz_ptr',
        ),
        migrations.RemoveField(
            model_name='piechart',
            name='vars',
        ),
        migrations.AlterUniqueTogether(
            name='piechartpart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='piechartpart',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='piechartpart',
            name='viz',
        ),
        migrations.RemoveField(
            model_name='pyramidchart',
            name='dataviz_ptr',
        ),
        migrations.RemoveField(
            model_name='pyramidchart',
            name='left_vars',
        ),
        migrations.RemoveField(
            model_name='pyramidchart',
            name='right_vars',
        ),
        migrations.AlterUniqueTogether(
            name='pyramidchartleftpart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pyramidchartleftpart',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='pyramidchartleftpart',
            name='viz',
        ),
        migrations.AlterUniqueTogether(
            name='pyramidchartrightpart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pyramidchartrightpart',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='pyramidchartrightpart',
            name='viz',
        ),
        migrations.RemoveField(
            model_name='scatterplot',
            name='dataviz_ptr',
        ),
        migrations.RemoveField(
            model_name='scatterplot',
            name='x_var',
        ),
        migrations.RemoveField(
            model_name='scatterplot',
            name='y_var',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='dataviz_ptr',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='vars',
        ),
        migrations.AlterUniqueTogether(
            name='sentencevariable',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sentencevariable',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='sentencevariable',
            name='viz',
        ),
        migrations.RemoveField(
            model_name='table',
            name='dataviz_ptr',
        ),
        migrations.RemoveField(
            model_name='table',
            name='vars',
        ),
        migrations.AlterUniqueTogether(
            name='tablevariable',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tablevariable',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='tablevariable',
            name='viz',
        ),
        migrations.AlterUniqueTogether(
            name='topicdataviz',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topicdataviz',
            name='data_viz',
        ),
        migrations.RemoveField(
            model_name='topicdataviz',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='vizes',
        ),
        migrations.DeleteModel(
            name='BarChart',
        ),
        migrations.DeleteModel(
            name='BarChartPart',
        ),
        migrations.DeleteModel(
            name='BigValue',
        ),
        migrations.DeleteModel(
            name='BigValueVariable',
        ),
        migrations.DeleteModel(
            name='DataViz',
        ),
        migrations.DeleteModel(
            name='Histogram',
        ),
        migrations.DeleteModel(
            name='LineChart',
        ),
        migrations.DeleteModel(
            name='LineChartPart',
        ),
        migrations.DeleteModel(
            name='MapLayer',
        ),
        migrations.DeleteModel(
            name='MiniMap',
        ),
        migrations.DeleteModel(
            name='PieChart',
        ),
        migrations.DeleteModel(
            name='PieChartPart',
        ),
        migrations.DeleteModel(
            name='PyramidChart',
        ),
        migrations.DeleteModel(
            name='PyramidChartLeftPart',
        ),
        migrations.DeleteModel(
            name='PyramidChartRightPart',
        ),
        migrations.DeleteModel(
            name='ScatterPlot',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.DeleteModel(
            name='SentenceVariable',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='TableVariable',
        ),
        migrations.DeleteModel(
            name='TopicDataViz',
        ),
        migrations.AddField(
            model_name='topicindicator',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_to_indicator', to='indicators.topic'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='vars',
            field=models.ManyToManyField(through='indicators.IndicatorVariable', to='indicators.Variable', verbose_name='Variables'),
        ),
        migrations.AddField(
            model_name='topic',
            name='inds',
            field=models.ManyToManyField(related_name='topic', through='indicators.TopicIndicator', to='indicators.Indicator'),
        ),
        migrations.AlterUniqueTogether(
            name='topicindicator',
            unique_together={('topic', 'indicator')},
        ),
    ]
