# Generated by Django 3.2 on 2022-05-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0018_auto_20220526_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorDataViz',
        ),
        migrations.DeleteModel(
            name='SubdomainIndicator',
        ),
    ]
