# Generated by Django 3.2 on 2021-04-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0020_auto_20210412_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentencevariable',
            options={},
        ),
        migrations.RemoveField(
            model_name='linechart',
            name='layout',
        ),
        migrations.AlterField(
            model_name='barchart',
            name='layout',
            field=models.CharField(choices=[('bar', 'Bar'), ('column', 'Column')], default='bar', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='sentencevariable',
            unique_together={('viz', 'variable', 'order')},
        ),
    ]
