# Generated by Django 3.2 on 2022-07-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0021_auto_20220624_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvariable',
            name='total',
            field=models.BooleanField(default=False, help_text="total's will be hidden from certain charts"),
        ),
    ]
