# Generated by Django 3.2 on 2021-04-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0021_auto_20210413_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_to_mini_map', to='indicators.variable'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='viz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_map_to_variable', to='indicators.minimap'),
        ),
    ]
