# Generated by Django 3.2 on 2022-07-14 21:04

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_auto_20220520_1523'),
        ('indicators', '0022_indicatorvariable_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description')),
                ('full_description', markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True)),
                ('context', models.ManyToManyField(blank=True, to='context.ContextItem')),
                ('tags', models.ManyToManyField(blank=True, to='context.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Indicator', 'verbose_name_plural': 'Indicators'},
        ),
        migrations.CreateModel(
            name='SubdomainTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomain_to_topic', to='indicators.subdomain')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_to_subdomain', to='indicators.topic')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('subdomain', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='subdomain',
            name='topics',
            field=models.ManyToManyField(related_name='subdomains', through='indicators.SubdomainTopic', to='indicators.Topic'),
        ),
        migrations.CreateModel(
            name='DomainSubdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_to_subdomain', to='indicators.domain')),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomain_to_domain', to='indicators.subdomain')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('domain', 'subdomain')},
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='subdomains',
            field=models.ManyToManyField(related_name='subdomains', through='indicators.DomainSubdomain', to='indicators.Subdomain'),
        ),
    ]
