# Generated by Django 3.2 on 2022-07-22 00:01

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0023_auto_20220714_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAxisTick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description')),
                ('full_description', markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True)),
                ('time_point', models.DateTimeField()),
                ('time_unit', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeAxisTimeAxisTick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_axis_to_time_axis_tick', to='indicators.timeaxis')),
                ('time_tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_axis_tick_to_time_axis', to='indicators.timeaxistick')),
            ],
        ),
        migrations.AddField(
            model_name='timeaxis',
            name='time_parts',
            field=models.ManyToManyField(through='indicators.TimeAxisTimeAxisTick', to='indicators.TimeAxisTick'),
        ),
    ]
