# Generated by Django 3.2 on 2021-04-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0023_auto_20210415_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigvalue',
            name='format',
            field=models.TextField(choices=[('PLN', 'Plain'), ('FRN', 'Plain'), ('PCT', 'Plain'), ('BTH', 'Number and Fraction')], default='PLN', max_length=3),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_to_mini_map', to='indicators.variable'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='viz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_map_to_variable', to='indicators.minimap'),
        ),
    ]
