# Generated by Django 3.2 on 2021-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0024_auto_20210420_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigvalue',
            name='format',
            field=models.TextField(choices=[('PLN', 'Plain'), ('FRN', 'Approximate, human friendly, fraction over denominator.'), ('PCT', 'Percent of denominator'), ('BTH', 'Number and Fraction')], default='PLN', help_text="Only use percent for numbers with denominators. Variables with 'percent' as a unit should use 'Plain'", max_length=3),
        ),
    ]
