# Generated by Django 3.2 on 2022-07-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0025_remove_timeaxis_time_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeaxis',
            name='axis_ticks',
            field=models.ManyToManyField(through='indicators.TimeAxisTimeAxisTick', to='indicators.TimeAxisTick'),
        ),
    ]
