# Generated by Django 3.2 on 2021-04-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0026_auto_20210430_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='minimap',
            options={},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.RemoveField(
            model_name='dataviz',
            name='polymorphic_ctype',
        ),
    ]
