# Generated by Django 3.2 on 2022-07-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0026_timeaxis_axis_ticks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeaxistimeaxistick',
            name='time_axis',
        ),
        migrations.RemoveField(
            model_name='timeaxistimeaxistick',
            name='time_tick',
        ),
        migrations.RemoveField(
            model_name='timeaxis',
            name='axis_ticks',
        ),
        migrations.DeleteModel(
            name='TimeAxisTick',
        ),
        migrations.DeleteModel(
            name='TimeAxisTimeAxisTick',
        ),
    ]
