# Generated by Django 3.2 on 2022-07-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0017_auto_20220303_2053'),
        ('indicators', '0027_auto_20220722_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorDatastore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_part_hash', models.IntegerField()),
                ('value', models.FloatField()),
                ('moe', models.FloatField()),
                ('denom', models.FloatField()),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('geog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.adminregion')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.variable')),
            ],
        ),
    ]
