# Generated by Django 3.2 on 2021-04-30 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('indicators', '0027_auto_20210430_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='minimap',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='dataviz',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_indicators.dataviz_set+', to='contenttypes.contenttype'),
        ),
    ]
