# Generated by Django 3.2 on 2021-05-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0028_auto_20210430_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckanregionalsource',
            name='county_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ckanregionalsource',
            name='county_field_is_sql',
            field=models.BooleanField(default=False),
        ),
    ]
