# Generated by Django 3.2 on 2022-07-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0017_auto_20220303_2053'),
        ('indicators', '0028_indicatordatastore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndicatorDatastore',
            new_name='CachedIndicatorData',
        ),
    ]
