# Generated by Django 3.2 on 2021-05-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0029_auto_20210510_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='legendType',
            new_name='legend_type',
        ),
    ]
