# Generated by Django 3.2 on 2022-07-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0029_rename_indicatordatastore_cachedindicatordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedindicatordata',
            name='time_part_hash',
            field=models.BigIntegerField(),
        ),
    ]
