# Generated by Django 3.2 on 2021-05-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0030_rename_legendtype_chart_legend_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimap',
            name='use_percent',
            field=models.BooleanField(default=False),
        ),
    ]
