# Generated by Django 3.2 on 2022-07-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0017_auto_20220303_2053'),
        ('indicators', '0030_alter_cachedindicatordata_time_part_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedindicatordata',
            name='time_part_hash',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterUniqueTogether(
            name='cachedindicatordata',
            unique_together={('geog', 'variable', 'time_part_hash')},
        ),
        migrations.AddIndex(
            model_name='cachedindicatordata',
            index=models.Index(fields=['variable', 'time_part_hash', 'geog'], name='indicators__variabl_b7ac20_idx'),
        ),
    ]
