# Generated by Django 3.2.3 on 2021-05-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_auto_20210513_1633'),
        ('indicators', '0031_minimap_use_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geogchoroplethmaplayer',
            name='sub_geog',
            field=models.ForeignKey(blank=True, help_text='If provided, this geography will be styled within the target geography. Otherwise, the provided geography will be styled along with others of the same level.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.censusgeography'),
        ),
    ]
