# Generated by Django 3.2 on 2022-07-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0031_auto_20220728_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedindicatordata',
            name='denom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cachedindicatordata',
            name='moe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cachedindicatordata',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
