# Generated by Django 3.2.5 on 2021-08-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0032_alter_geogchoroplethmaplayer_sub_geog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='aggregation_method',
            field=models.CharField(choices=[('NONE', 'None'), ('COUNT', 'Count'), ('SUM', 'Sum'), ('AVG', 'Mean'), ('MODE', 'Mode'), ('MAX', 'Maximum'), ('MIN', 'Minimum')], default='SUM', help_text='Select "None" if this value cannot be used in aggregate.', max_length=5),
        ),
    ]
