# Generated by Django 3.2 on 2022-07-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0032_auto_20220728_2016'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cachedindicatordata',
            name='indicators__variabl_b7ac20_idx',
        ),
        migrations.AlterField(
            model_name='cachedindicatordata',
            name='geog',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cachedindicatordata',
            name='time_part_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cachedindicatordata',
            name='variable',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='timeaxis',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AddIndex(
            model_name='cachedindicatordata',
            index=models.Index(fields=['variable', 'time_part_hash', 'geog'], name='indicators__variabl_750a26_idx'),
        ),
    ]
