# Generated by Django 3.2 on 2022-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0033_auto_20220728_2055'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cachedindicatordata',
            index=models.Index(fields=['expiration'], name='indicators__expirat_f3b150_idx'),
        ),
    ]
