# Generated by Django 3.2.5 on 2021-08-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0034_auto_20210820_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minimap',
            name='use_percent',
        ),
        migrations.AddField(
            model_name='maplayer',
            name='use_percent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible by default'),
        ),
    ]
