# Generated by Django 3.2 on 2022-10-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0018_auto_20220729_1552'),
        ('indicators', '0034_cachedindicatordata_indicators__expirat_f3b150_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='geographic_extent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.adminregion'),
        ),
    ]
