# Generated by Django 3.2 on 2022-11-10 18:48

from django.db import migrations, models
import maps.models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0035_source_geographic_extent'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvariable',
            name='color_scale',
            field=models.CharField(choices=[('YlGn', 'Yellow-Green [sequential] (ColorBrewer)'), ('YlGnBu', 'Yellow-Green-Blue [sequential] (ColorBrewer)'), ('GnBu', 'Green-Blue [sequential] (ColorBrewer)'), ('BuGn', 'Blue-Green [sequential] (ColorBrewer)'), ('PuBuGn', 'Purple-Blue-Green [sequential] (ColorBrewer)'), ('PuBu', 'Purple-Blue [sequential] (ColorBrewer)'), ('BuPu', 'Blue-Purple [sequential] (ColorBrewer)'), ('RdPu', 'Red-Purple [sequential] (ColorBrewer)'), ('PuRd', 'Purple-Red [sequential] (ColorBrewer)'), ('OrRd', 'Orange-Red [sequential] (ColorBrewer)'), ('YlOrRd', 'Yellow-Orange-Red [sequential] (ColorBrewer)'), ('YlOrBr', 'Yellow-Orange-Brown [sequential] (ColorBrewer)'), ('Purples', 'Purples [sequential] (ColorBrewer)'), ('Blues', 'Blues [sequential] (ColorBrewer)'), ('Greens', 'Greens [sequential] (ColorBrewer)'), ('Oranges', 'Oranges [sequential] (ColorBrewer)'), ('Reds', 'Reds [sequential] (ColorBrewer)'), ('Greys', 'Greys [sequential] (ColorBrewer)'), ('PuOr', 'Purple-Orange [divergent] (ColorBrewer)'), ('BrBG', 'Brown-BlueGreen [divergent] (ColorBrewer)'), ('PRGn', 'PRGreen [divergent] (ColorBrewer)'), ('PiYG', 'Pink-YellowGreen [divergent] (ColorBrewer)'), ('RdBu', 'Red-Blue [divergent] (ColorBrewer)'), ('RdGy', 'Red-Grey [divergent] (ColorBrewer)'), ('RdYlBu', 'Red-Yellow-Blue [divergent] (ColorBrewer)'), ('Spectral', 'Spectral [divergent] (ColorBrewer)'), ('RdYlGn', 'Red-Yellow-Green [divergent] (ColorBrewer)'), ('Accent', 'Accent [qualitative] (ColorBrewer)'), ('Dark2', 'Dark2 [qualitative] (ColorBrewer)'), ('Paired', 'Paired [qualitative] (ColorBrewer)'), ('Pastel1', 'Pastel1 [qualitative] (ColorBrewer)'), ('Pastel2', 'Pastel2 [qualitative] (ColorBrewer)'), ('Set1', 'Set1 [qualitative] (ColorBrewer)'), ('Set2', 'Set2 [qualitative] (ColorBrewer)'), ('Set3', 'Set3 [qualitative] (ColorBrewer)')], default=maps.models.random_color_scale, max_length=100),
        ),
    ]
