# Generated by Django 3.2.5 on 2021-09-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0036_alter_variable_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='domain',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
