# Generated by Django 3.2.7 on 2021-09-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0038_auto_20210924_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
