# Generated by Django 3.2.7 on 2021-09-24 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0040_remove_subdomain_indicators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='subdomain',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='subdomainindicator',
            options={'ordering': ('order',)},
        ),
        migrations.CreateModel(
            name='IndicatorDataViz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('data_viz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataviz_to_indicator', to='indicators.dataviz')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_to_dataviz', to='indicators.indicator')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='vizes',
            field=models.ManyToManyField(related_name='new_indicator', through='indicators.IndicatorDataViz', to='indicators.DataViz'),
        ),
    ]
