# Generated by Django 3.2.7 on 2021-09-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0041_auto_20210924_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_data_vizes', to='indicators.indicator'),
        ),
    ]
