# Generated by Django 3.2.7 on 2021-09-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0042_alter_dataviz_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='layout',
        ),
    ]
