# Generated by Django 3.2.7 on 2021-11-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectidentifier_id', models.CharField(max_length=100)),
                ('projectindex_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'datastore.ba6b156f-82fe-41b0-83b9-c17540836598',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectidentifier_id', models.CharField(max_length=100)),
                ('projectindex_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'datastore.25c0e399-0ad8-42cf-8899-e6f35faf1187',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FHALoanID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectidentifier_id', models.CharField(max_length=100)),
                ('projectindex_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'datastore.64449027-404c-48fb-a9a4-75e9e8d14188',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LIHTCProjectID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectidentifier_id', models.CharField(max_length=100)),
                ('projectindex_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'datastore.e5b27187-b134-4050-8101-db4e19ffdb30',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NormalizeStateID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectidentifier_id', models.CharField(max_length=100)),
                ('projectindex_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'datastore.f71eb9f3-c413-47a3-8592-af447fe93020',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PMIndx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectidentifier_id', models.CharField(max_length=100)),
                ('projectindex_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'datastore.6234dd27-79f4-43d3-b098-19f12692ce55',
                'managed': False,
            },
        ),
    ]
