# Generated by Django 3.2.7 on 2021-11-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_housing', '0002_contractid_developmentcode_fhaloanid_lihtcprojectid_normalizestateid_pmindx'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contractid',
            table='"datastore"."ba6b156f-82fe-41b0-83b9-c17540836598"',
        ),
    ]
