# Generated by Django 3.2.7 on 2021-11-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_housing', '0003_alter_contractid_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fhaloanid',
            table='datastore.',
        ),
    ]
