# Generated by Django 3.2.7 on 2021-11-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_housing', '0004_alter_fhaloanid_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fhaloanid',
            table='datastore.64449027-404c-48fb-a9a4-75e9e8d14188',
        ),
    ]
