# Generated by Django 3.2.7 on 2021-11-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_housing', '0005_alter_fhaloanid_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activehudmultifamilyinsuredmortgages',
            table='931d45da-f791-46c4-998b-60bafa904b36',
        ),
        migrations.AlterModelTable(
            name='allbuildingsfromlihtcprojects',
            table='ad49ed19-1122-4f9d-a3c2-491f36a293f4',
        ),
        migrations.AlterModelTable(
            name='contractid',
            table='ba6b156f-82fe-41b0-83b9-c17540836598',
        ),
        migrations.AlterModelTable(
            name='demographicsbyhousingprojectfromphfa',
            table='fcb7cd5d-71f6-4f38-bb78-a3002be47ed6',
        ),
        migrations.AlterModelTable(
            name='developmentcode',
            table='25c0e399-0ad8-42cf-8899-e6f35faf1187',
        ),
        migrations.AlterModelTable(
            name='fhaloanid',
            table='64449027-404c-48fb-a9a4-75e9e8d14188',
        ),
        migrations.AlterModelTable(
            name='hudinspectionscores',
            table='a768bb6b-9d1e-463f-9711-651fedf971fb',
        ),
        migrations.AlterModelTable(
            name='hudinsuredmultifamilyproperties',
            table='c099b5b9-df5d-4380-9cb3-6c45b03ac8b4',
        ),
        migrations.AlterModelTable(
            name='hudmultifamilyfiscalyearproduction',
            table='b3ff057c-1518-4a34-a004-39d3d49a5ad7',
        ),
        migrations.AlterModelTable(
            name='hudmultifamilyinspectionscores',
            table='7d4ad5ee-7229-4aa6-b3a2-69779fe5c52a',
        ),
        migrations.AlterModelTable(
            name='hudpublichousingbuildings',
            table='6269354d-bac6-4c2e-ad07-2dd7e2ab252e',
        ),
        migrations.AlterModelTable(
            name='hudpublichousingdevelopments',
            table='7cc60ad7-b209-46f2-bdda-9755d8a42461',
        ),
        migrations.AlterModelTable(
            name='lihtc',
            table='d5275180-13f1-460b-b933-aab6afc2966e',
        ),
        migrations.AlterModelTable(
            name='lihtcdatafromphfa',
            table='f6a77bc1-e3c1-403a-86bc-40b906124af6',
        ),
        migrations.AlterModelTable(
            name='lihtcprojectid',
            table='e5b27187-b134-4050-8101-db4e19ffdb30',
        ),
        migrations.AlterModelTable(
            name='multifamilyassistanceandsection8contracts',
            table='438a732d-c86f-4a06-bff8-61eb6ebe7328',
        ),
        migrations.AlterModelTable(
            name='normalizestateid',
            table='f71eb9f3-c413-47a3-8592-af447fe93020',
        ),
        migrations.AlterModelTable(
            name='phfastats',
            table='a6b93b7b-e04e-42c9-96f9-ee788e4f0978',
        ),
        migrations.AlterModelTable(
            name='pmindx',
            table='6234dd27-79f4-43d3-b098-19f12692ce55',
        ),
        migrations.AlterModelTable(
            name='subsidyextractfromhudinsuredmultifamilyproperties',
            table='7eeabaa5-bd27-4df0-9459-d56acd826451',
        ),
        migrations.AlterModelTable(
            name='subsidyextractfrommultifamilyassistanceandsection8contracts',
            table='127d12cd-9718-4b44-9cc1-2673a1a50dba',
        ),
    ]
