# Generated by Django 3.2.7 on 2021-11-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_housing', '0006_auto_20211111_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectindex',
            options={'managed': False},
        ),
    ]
