# Generated by Django 3.2.7 on 2021-11-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_housing', '0007_alter_projectindex_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectindex',
            table='1885161c-65f3-4cb2-98aa-4402487ae888',
        ),
    ]
