# Generated by Django 3.2 on 2022-03-14 22:29

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_housing', '0010_account_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='description',
            field=models.TextField(blank=True, help_text='1 or 2 sentences', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='full_description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full description with markdown functionality.', null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
