# Generated by Django 3.2 on 2022-03-14 22:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_housing', '0011_auto_20220314_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
