# Generated by Django 3.2 on 2022-05-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_housing', '0012_alter_watchlist_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hudinspectionscores',
            options={'managed': False, 'ordering': ['-inspection_date']},
        ),
        migrations.AlterModelOptions(
            name='hudinsuredmultifamilyproperties',
            options={'managed': False, 'ordering': ['-initial_endorsement_date']},
        ),
        migrations.AlterModelOptions(
            name='hudmultifamilyinspectionscores',
            options={'managed': False, 'ordering': ['-inspection_date']},
        ),
        migrations.AlterModelOptions(
            name='multifamilyassistanceandsection8contracts',
            options={'managed': False, 'ordering': ['-subsidy_expiration_date']},
        ),
        migrations.AlterModelOptions(
            name='subsidyextractfromhudinsuredmultifamilyproperties',
            options={'managed': False, 'ordering': ['-subsidy_expiration_date']},
        ),
        migrations.AlterModelOptions(
            name='subsidyextractfrommultifamilyassistanceandsection8contracts',
            options={'managed': False, 'ordering': ['-owner_effective_date']},
        ),
    ]
