# Generated by Django 3.2 on 2022-07-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_housing', '0014_auto_20220728_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
