# Generated by Django 3.1.5 on 2021-01-28 21:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('CEN', 'Decennial Census'), ('ACS5', 'ACS 5-year'), ('ACS1', 'ACS 1-year')], default='CEN', max_length=4)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2021)])),
                ('table_id', models.CharField(db_index=True, max_length=15)),
                ('description', models.CharField(db_index=True, max_length=500)),
            ],
            options={
                'unique_together': {('year', 'dataset', 'table_id')},
            },
        ),
        migrations.CreateModel(
            name='CensusValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('raw_value', models.CharField(blank=True, max_length=20, null=True)),
                ('census_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census_data.censustable')),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.geography')),
            ],
            options={
                'unique_together': {('geography', 'census_table')},
                'index_together': {('geography', 'census_table')},
            },
        ),
    ]
