# Generated by Django 3.2.7 on 2021-10-21 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census_data', '0002_auto_20211009_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusTableRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=15)),
                ('dataset', models.CharField(choices=[('CEN', 'Decennial Census'), ('ACS5', 'ACS 5-year'), ('ACS1', 'ACS 1-year')], default='CEN', max_length=4)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2021)])),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='censustablepointer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='censustablepointer',
            name='moe_table',
        ),
        migrations.RemoveField(
            model_name='censustablepointer',
            name='value_table',
        ),
        migrations.DeleteModel(
            name='CensusTable',
        ),
    ]
