# Generated by Django 3.2.7 on 2021-10-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census_data', '0003_auto_20211021_2006'),
        ('indicators', '0002_auto_20211021_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CensusTablePointer',
        ),
        migrations.AlterUniqueTogether(
            name='censustablerecord',
            unique_together={('table_id', 'dataset', 'year')},
        ),
        migrations.AlterIndexTogether(
            name='censustablerecord',
            index_together={('table_id', 'dataset', 'year')},
        ),
    ]
