# Generated by Django 3.2.9 on 2022-01-06 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census_data', '0004_auto_20211021_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censustablerecord',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
