# Generated by Django 3.1.5 on 2021-02-25 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('census_data', '0004_censustablepointer_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusvalue',
            name='geography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.censusgeography'),
        ),
    ]
