# Generated by Django 3.2.7 on 2021-10-06 15:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('mini_geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('geom_webmercator', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857)),
                ('in_extent', models.BooleanField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('common_geoid', models.CharField(blank=True, max_length=21, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_geo.adminregion_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('adminregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.adminregion')),
                ('geoid', models.CharField(max_length=20)),
                ('affgeoid', models.CharField(max_length=21, unique=True)),
                ('lsad', models.CharField(max_length=2)),
                ('aland', models.BigIntegerField(verbose_name='Area (land)')),
                ('awater', models.BigIntegerField(verbose_name='Area (water)')),
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=3)),
                ('tractce', models.CharField(max_length=6)),
                ('blkgrpce', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Block Groups',
            },
            bases=('geo.adminregion', models.Model),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('adminregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.adminregion')),
                ('affgeoid', models.CharField(max_length=21, unique=True)),
                ('lsad', models.CharField(max_length=2)),
                ('aland', models.BigIntegerField(verbose_name='Area (land)')),
                ('awater', models.BigIntegerField(verbose_name='Area (water)')),
                ('geoid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=5)),
                ('countyns', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
            bases=('geo.adminregion', models.Model),
        ),
        migrations.CreateModel(
            name='CountySubdivision',
            fields=[
                ('adminregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.adminregion')),
                ('geoid', models.CharField(max_length=20)),
                ('affgeoid', models.CharField(max_length=21, unique=True)),
                ('lsad', models.CharField(max_length=2)),
                ('aland', models.BigIntegerField(verbose_name='Area (land)')),
                ('awater', models.BigIntegerField(verbose_name='Area (water)')),
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=3)),
                ('cousubfp', models.CharField(max_length=5)),
                ('cousubns', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'County Subdivisions',
            },
            bases=('geo.adminregion', models.Model),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('adminregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.adminregion')),
            ],
            options={
                'verbose_name': 'Neighborhood',
                'verbose_name_plural': 'Neighborhoods',
            },
            bases=('geo.adminregion',),
        ),
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('adminregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.adminregion')),
                ('geoid', models.CharField(max_length=20)),
                ('affgeoid', models.CharField(max_length=21, unique=True)),
                ('lsad', models.CharField(max_length=2)),
                ('aland', models.BigIntegerField(verbose_name='Area (land)')),
                ('awater', models.BigIntegerField(verbose_name='Area (water)')),
                ('statefp', models.CharField(max_length=2)),
                ('unsdlea', models.CharField(max_length=5)),
                ('placens', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'School Districts',
            },
            bases=('geo.adminregion', models.Model),
        ),
        migrations.CreateModel(
            name='Tract',
            fields=[
                ('adminregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.adminregion')),
                ('geoid', models.CharField(max_length=20)),
                ('affgeoid', models.CharField(max_length=21, unique=True)),
                ('lsad', models.CharField(max_length=2)),
                ('aland', models.BigIntegerField(verbose_name='Area (land)')),
                ('awater', models.BigIntegerField(verbose_name='Area (water)')),
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=3)),
                ('tractce', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Tracts',
            },
            bases=('geo.adminregion', models.Model),
        ),
        migrations.CreateModel(
            name='ZipCodeTabulationArea',
            fields=[
                ('adminregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.adminregion')),
                ('geoid', models.CharField(max_length=20)),
                ('affgeoid', models.CharField(max_length=21, unique=True)),
                ('lsad', models.CharField(max_length=2)),
                ('aland', models.BigIntegerField(verbose_name='Area (land)')),
                ('awater', models.BigIntegerField(verbose_name='Area (water)')),
                ('zctace', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Zip Code Tabulation Area',
                'verbose_name_plural': 'Zip Code Tabulation Areas',
            },
            bases=('geo.adminregion', models.Model),
        ),
    ]
