# Generated by Django 3.2.7 on 2021-10-07 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminregion',
            name='in_extent',
        ),
    ]
