# Generated by Django 3.2 on 2021-04-21 22:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_neighborhood_zipcodetabulationarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='child_geog_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NONE', 'N/A'), ('BLOCKGROUP', 'Block group'), ('TRACT', 'Tract'), ('COUNTY_SUBDIVISION', 'County Subdivision'), ('COUNTY', 'County'), ('PLACE', 'Place'), ('PUMA', 'PUMA'), ('STATE_HOUSE', 'State House'), ('STATE_SENATE', 'State Senate'), ('ZCTA', 'Zip Code Tabulation Area'), ('NEIGHBORHOOD', 'Neighborhood')], max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='geography',
            name='geo_level',
            field=models.CharField(blank=True, choices=[('NONE', 'N/A'), ('BLOCKGROUP', 'Block group'), ('TRACT', 'Tract'), ('COUNTY_SUBDIVISION', 'County Subdivision'), ('COUNTY', 'County'), ('PLACE', 'Place'), ('PUMA', 'PUMA'), ('STATE_HOUSE', 'State House'), ('STATE_SENATE', 'State Senate'), ('ZCTA', 'Zip Code Tabulation Area'), ('NEIGHBORHOOD', 'Neighborhood')], default='NONE', max_length=30),
        ),
    ]
