# Generated by Django 3.2.7 on 2021-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_remove_adminregion_in_extent'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregion',
            name='in_extent',
            field=models.BooleanField(null=True),
        ),
    ]
