# Generated by Django 3.2 on 2021-04-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20210421_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geography',
            name='child_geog_levels',
        ),
    ]
