# Generated by Django 3.2.7 on 2021-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20211026_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubRegionRelation',
            new_name='SubregionsRelation',
        ),
        migrations.RemoveField(
            model_name='adminregion',
            name='child_geogs',
        ),
        migrations.AddField(
            model_name='adminregion',
            name='subregions',
            field=models.ManyToManyField(through='geo.SubregionsRelation', to='geo.AdminRegion'),
        ),
    ]
