# Generated by Django 3.2 on 2021-04-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_remove_geography_child_geog_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='geo_level',
            field=models.CharField(blank=True, choices=[('NONE', 'N/A'), ('blockGroup', 'Block group'), ('tract', 'Tract'), ('countySubdivision', 'County Subdivision'), ('county', 'County'), ('place', 'Place'), ('puma', 'PUMA'), ('stateHouse', 'State House'), ('stateSenate', 'State Senate'), ('zcta', 'Zip Code Tabulation Area'), ('neighborhood', 'Neighborhood')], default='NONE', max_length=30),
        ),
    ]
