# Generated by Django 3.2.7 on 2021-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20211026_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subregionsrelation',
            name='geog_type',
            field=models.CharField(choices=[('blockGroup', 'Block group'), ('tract', 'Tract'), ('countySubdivision', 'County subdivision'), ('place', 'Place'), ('puma', 'Puma'), ('schoolDistrict', 'School district'), ('stateHouse', 'State house'), ('stateSenate', 'State senate'), ('county', 'County'), ('zcta', 'Zip Code Tab. Area (Zip Code)'), ('neighborhood', 'Pgh Neighborhood')], max_length=64),
        ),
    ]
