# Generated by Django 3.2.7 on 2021-10-27 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_alter_subregionsrelation_geog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subregionsrelation',
            name='child_regions',
        ),
        migrations.AddField(
            model_name='subregionsrelation',
            name='sub_regions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
