# Generated by Django 3.2.7 on 2021-10-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_auto_20211027_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminregion',
            name='subregions',
        ),
        migrations.AddField(
            model_name='adminregion',
            name='sub_regions',
            field=models.JSONField(default=dict),
        ),
    ]
