# Generated by Django 3.2 on 2021-05-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0025_alter_bigvalue_format'),
        ('census_data', '0005_auto_20210225_0133'),
        ('geo', '0007_auto_20210505_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcodetabulationarea',
            name='censusgeography_ptr',
        ),
        migrations.AlterField(
            model_name='geography',
            name='geo_level',
            field=models.CharField(blank=True, choices=[('NONE', 'N/A'), ('BLOCKGROUP', 'Block group'), ('TRACT', 'Tract'), ('COUNTY_SUBDIVISION', 'County Subdivision'), ('COUNTY', 'County'), ('PLACE', 'Place'), ('PUMA', 'PUMA'), ('STATE_HOUSE', 'State House'), ('STATE_SENATE', 'State Senate'), ('SCHOOL_DISTRICT', 'School District')], default='NONE', max_length=30),
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
        migrations.DeleteModel(
            name='ZipCodeTabulationArea',
        ),
    ]
