# Generated by Django 3.2 on 2021-05-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_auto_20210505_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('censusgeography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.censusgeography')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('geo.censusgeography',),
        ),
        migrations.CreateModel(
            name='ZipCodeTabulationArea',
            fields=[
                ('censusgeography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.censusgeography')),
                ('zctace', models.CharField(max_length=5)),
                ('geoid', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Zip Code Tabulation Area',
                'verbose_name_plural': 'Zip Code Tabulation Areas',
            },
            bases=('geo.censusgeography',),
        ),
        migrations.AlterField(
            model_name='geography',
            name='geo_level',
            field=models.CharField(blank=True, choices=[('NONE', 'N/A'), ('blockGroup', 'Block group'), ('tract', 'Tract'), ('countySubdivision', 'County Subdivision'), ('county', 'County'), ('place', 'Place'), ('puma', 'PUMA'), ('stateHouse', 'State House'), ('stateSenate', 'State Senate'), ('zcta', 'Zip Code Tabulation Area'), ('neighborhood', 'Neighborhood')], default='NONE', max_length=30),
        ),
    ]
