# Generated by Django 3.2.7 on 2021-10-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_auto_20211027_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminregion',
            old_name='sub_regions',
            new_name='subregions',
        ),
        migrations.DeleteModel(
            name='SubregionsRelation',
        ),
    ]
