# Generated by Django 3.2.3 on 2021-05-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_auto_20210510_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'verbose_name': 'Zip Code Tabulation Area', 'verbose_name_plural': 'Zip Code Tabulation Areas'},
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='geoid',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='censusgeography_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.censusgeography'),
        ),
    ]
