# Generated by Django 3.2.7 on 2021-10-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_auto_20211027_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregion',
            name='common_geoid',
            field=models.CharField(blank=True, db_index=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='adminregion',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
