# Generated by Django 3.2.3 on 2021-05-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_auto_20210510_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'verbose_name': 'Zip Code Tabulation Area', 'verbose_name_plural': 'Zip Code Tabulation Areas'},
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='geoid',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
