# Generated by Django 3.2.7 on 2021-11-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_auto_20211027_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminregion',
            old_name='common_geoid',
            new_name='global_geoid',
        ),
    ]
