# Generated by Django 3.2.3 on 2021-05-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_auto_20210526_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='censusgeography_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.censusgeography'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='geoid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
