# Generated by Django 3.2.3 on 2021-06-02 15:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_auto_20210527_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='mini_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
