# Generated by Django 3.2.9 on 2022-01-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_adminregion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregion',
            name='geog_type',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True),
        ),
    ]
