# Generated by Django 3.2.3 on 2021-06-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_geography_mini_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'verbose_name': 'Neighborhood', 'verbose_name_plural': 'Neighborhoods'},
        ),
        migrations.AlterField(
            model_name='zipcodetabulationarea',
            name='censusgeography_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geo.censusgeography'),
        ),
        migrations.AlterField(
            model_name='zipcodetabulationarea',
            name='geoid',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
