# Generated by Django 3.2.9 on 2022-01-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0013_adminregion_geog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregion',
            name='title',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True),
        ),
    ]
