# Generated by Django 3.2.5 on 2021-08-27 18:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0013_auto_20210603_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='geom_webmercator',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857),
        ),
    ]
