# Generated by Django 3.2.9 on 2022-01-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0014_adminregion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregion',
            name='geog_type',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adminregion',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
