# Generated by Django 3.2.5 on 2021-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0014_geography_geom_webmercator'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='in_extent',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
    ]
