# Generated by Django 3.2.9 on 2022-01-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0015_auto_20220107_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminregion',
            name='title',
        ),
    ]
