# Generated by Django 3.2 on 2022-03-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0016_remove_adminregion_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['name'], 'verbose_name': 'Neighborhood', 'verbose_name_plural': 'Neighborhoods'},
        ),
        migrations.AlterModelOptions(
            name='zipcodetabulationarea',
            options={'ordering': ['name'], 'verbose_name': 'Zip Code Tabulation Area', 'verbose_name_plural': 'Zip Code Tabulation Areas'},
        ),
    ]
