# Generated by Django 3.2 on 2022-11-08 16:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0018_auto_20220729_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregion',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
